### ISSUE TITLE
Not compatible with ownCoud 10.2

### ISSUE THREAD

**Issue by cdamken** [Yetangitu/owncloud-apps#119]
The class that was deprecated since OC 8.0.0: OCP\Config, OCP\PERMISSION_XXX, OCP\Template 

https://github.com/owncloud/core/pull/34927

**Comment by cdamken** [comment]
```
Error: Class 'OCA\Files_Reader\OC' not found
#7 files_reader/lib/config.php(28): get
#6 files_reader/lib/Hooks.php(41): announce_settings
#5 /var/www/owncloud/lib/private/legacy/hook.php(105): emit
#4 /var/www/owncloud/core/js/config.php(222): require_once
#3 /var/www/owncloud/lib/private/Route/Route.php(155): OC\Route\{closure}
#2 /var/www/owncloud/lib/private/Route/Router.php(342): match
#1 /var/www/owncloud/lib/base.php(909): handleRequest
#0 /var/www/owncloud/index.php(54): null
```

**Comment by ho4ho** [comment]
@cdamken Why 10.2.0 broke ?

> The next minor version (which could be 10.2.0) will bring new features. All apps will continue working as before. API functionality is only expanded, not reduced.

https://owncloud.org/news/switching-owncloud-to-semantic-versioning-semver/

**Comment by ho4ho** [comment]
Maybe fix also in https://github.com/Yetangitu/owncloud-apps/pull/109 https://github.com/Yetangitu/owncloud-apps/pull/108 ?

**Comment by cdamken** [comment]
> @cdamken Why 10.2.0 broke ?

The deprecated classes were removed.

**Comment by cdamken** [comment]
> Maybe fix also in #109, #108 ?

I doubt it, I don't see those classes in ownCloud.

**Comment by cdamken** [comment]
@Yetangitu Will you provide a new release?

I liked this app a lot, I really miss using it
